In [1]:
#importing the libaries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the dataset
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset)

In [5]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [6]:
dataset = dataset.astype({
    'sex_female': int,
    'sex_male': int,
    'smoker_no': int,
    'smoker_yes': int,
})

In [7]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,1,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0
2,28,33.000,3,4449.46200,0,1,1,0
3,33,22.705,0,21984.47061,0,1,1,0
4,32,28.880,0,3866.85520,0,1,1,0
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0
1334,18,31.920,0,2205.98080,1,0,1,0
1335,18,36.850,0,1629.83350,1,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0
1337,61,29.070,0,29141.36030,1,0,0,1

In [8]:
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)

In [9]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,1,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0
2,28,33.000,3,4449.46200,0,1,1,0
3,33,22.705,0,21984.47061,0,1,1,0
4,32,28.880,0,3866.85520,0,1,1,0
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0
1334,18,31.920,0,2205.98080,1,0,1,0
1335,18,36.850,0,1629.83350,1,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0
1337,61,29.070,0,29141.36030,1,0,0,1

In [10]:
dataset.drop(columns=['sex_female'], inplace=True)

In [11]:
dataset

      age     bmi  children      charges  sex_male  smoker_no  smoker_yes
0      19  27.900         0  16884.92400         0          0           1
1      18  33.770         1   1725.55230         1          1           0
2      28  33.000         3   4449.46200         1          1           0
3      33  22.705         0  21984.47061         1          1           0
4      32  28.880         0   3866.85520         1          1           0
...   ...     ...       ...          ...       ...        ...         ...
1333   50  30.970         3  10600.54830         1          1           0
1334   18  31.920         0   2205.98080         0          1           0
1335   18  36.850         0   1629.83350         0          1           0
1336   21  25.800         0   2007.94500         0          1           0
1337   61  29.070         0  29141.36030         0          0           1

[1338 rows x 7 columns]

In [12]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_no',
       'smoker_yes'],
      dtype='object')

In [13]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_no',
       'smoker_yes']]

In [14]:
independent

      age     bmi  children  sex_male  smoker_no  smoker_yes
0      19  27.900         0         0          0           1
1      18  33.770         1         1          1           0
2      28  33.000         3         1          1           0
3      33  22.705         0         1          1           0
4      32  28.880         0         1          1           0
...   ...     ...       ...       ...        ...         ...
1333   50  30.970         3         1          1           0
1334   18  31.920         0         0          1           0
1335   18  36.850         0         0          1           0
1336   21  25.800         0         0          1           0
1337   61  29.070         0         0          0           1

[1338 rows x 6 columns]

In [15]:
dependent=dataset[['charges']]

In [16]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
#split into training  set and test
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','ploy','sigmoid','linear'],'C':[10, 100, 1000, 2000, 3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit= True, verbose= 3, n_jobs=-1)

# fitting the model for gridsearch
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
50 fits failed out of a total of 200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'linear', 'sigmoid', 'precomputed', 'poly', 'rbf'} or a callable. Got 'ploy' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'linear', 'rbf', 'precomputed', 'sigmoid', 'poly'} or a callable. Got 'ploy' instead.

--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'linear', 'poly', 'rbf', 'precomputed', 'sigmoid'} or a callable. Got 'ploy' instead.

--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'linear', 'sigmoid', 'poly', 'rbf', 'precomputed'} or a callable. Got 'ploy' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'sigmoid', 'rbf', 'linear', 'precomputed', 'poly'} or a callable. Got 'ploy' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'poly', 'linear', 'rbf', 'precomputed', 'sigmoid'} or a callable. Got 'ploy' instead.

--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'linear', 'rbf', 'poly', 'precomputed', 'sigmoid'} or a callable. Got 'ploy' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'precomputed', 'poly', 'linear', 'rbf', 'sigmoid'} or a callable. Got 'ploy' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "E:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "E:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVR must be a str among {'rbf', 'linear', 'sigmoid', 'precomputed', 'poly'} or a callable. Got 'ploy' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
E:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [-0.04075042         nan  0.03689692  0.50424747 -0.04075881         nan
  0.03686412  0.50424747  0.33289572         nan  0.49886783  0.59377681
  0.33272358         nan  0.4988983   0.59377681  0.73672274         nan
  0.17568439  0.59547168  0.73665529         nan  0.17107943  0.59547168
  0.79068163         nan -0.59239456  0.59513285  0.79063883         nan
 -0.59075743  0.59513285  0.79794175         nan -1.90570411  0.59445873
  0.79788968         nan -1.92512468  0.59445873]
  warnings.warn(
E:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'ploy', 'sigmoid', 'linear']},
             verbose=3)

In [21]:
# print best parameter after tuning
print (grid.best_params_)
re=grid.cv_results_
print("The R_Score value for best parameter {}:".format(grid.best_params_))

{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}
The R_Score value for best parameter {'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}:

In [22]:
table=pd.DataFrame.from_dict(re)

In [23]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.597568,0.215632,0.169281,0.055129,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.012793,0.036967,-0.101105,-0.064370,-0.088037,-0.040750,0.055396,25
1,0.008206,0.004835,0.000000,0.000000,10,auto,ploy,"{'C': 10, 'gamma': 'auto', 'kernel': 'ploy'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
2,0.423253,0.147391,0.071036,0.020139,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.088356,0.113585,-0.023976,0.018426,-0.011907,0.036897,0.054695,23
3,0.253896,0.019408,0.058512,0.016607,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.521674,0.574533,0.471297,0.503816,0.449918,0.504247,0.043084,15
4,0.386392,0.081060,0.200503,0.020150,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.013248,0.036934,-0.101402,-0.064406,-0.088168,-0.040759,0.055565,26
5,0.006523,0.003126,0.000000,0.000000,10,scale,ploy,"{'C': 10, 'gamma': 'scale', 'kernel': 'ploy'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
6,0.544519,0.057960,0.108525,0.034837,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.087065,0.113678,-0.023382,0.018521,-0.011561,0.036864,0.054280,24
7,0.364580,0.029753,0.035488,0.008066,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.521674,0.574533,0.471297,0.503816,0.449918,0.504247,0.043084,15
8,0.431439,0.046793,0.208974,0.019984,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.405838,0.403672,0.271578,0.321315,0.262075,0.332896,0.062031,19
9,0.004126,0.002456,0.000000,0.000000,100,auto,ploy,"{'C': 100, 'gamma': 'auto', 'kernel': 'ploy'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
10,0.562497,0.088307,0.101498,0.043936,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.518016,0.564768,0.470056,0.486874,0.454626,0.498868,0.039091,18
11,0.443495,0.071965,0.068673,0.032234,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.601687,0.643605,0.578833,0.596284,0.548474,0.593777,0.031072,13
12,0.419565,0.029265,0.167267,0.012877,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.407874,0.403536,0.269630,0.321151,0.261427,0.332724,0.063024,20
13,0.007268,0.008400,0.000000,0.000000,100,scale,ploy,"{'C': 100, 'gamma': 'scale', 'kernel': 'ploy'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
14,0.570361,0.060693,0.134971,0.028434,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.518597,0.564821,0.468954,0.487731,0.454389,0.498898,0.039335,17
15,0.514350,0.062266,0.080759,0.050415,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.601687,0.643605,0.578833,0.596284,0.548474,0.593777,0.031072,13
16,0.613977,0.053352,0.203584,0.031902,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.772752,0.741135,0.741923,0.763400,0.664404,0.736723,0.038174,5
17,0.006685,0.008093,0.000000,0.000000,1000,auto,ploy,"{'C': 1000, 'gamma': 'auto', 'kernel': 'ploy'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
18,0.678578,0.067824,0.123489,0.014983,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.170763,0.275032,0.067009,0.089799,0.275818,0.175684,0.088439,21
19,0.754625,0.036376,0.063795,0.017641,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.669960,0.591502,0.586922,0.572859,0.556116,0.595472,0.039237,7
20,0.659689,0.015741,0.186783,0.010700,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.773475,0.741083,0.741346,0.763298,0.664075,0.736655,0.038406,6
21,0.011025,0.008691,0.000000,0.000000,1000,scale,ploy,"{'C': 1000, 'gamma': 'scale', 'kernel': 'ploy'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
22,0.638921,0.032208,0.084555,0.021831,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.183911,0.272788,0.056621,0.088664,0.253414,0.171079,0.086234,22
23,0.600744,0.073646,0.069221,0.023342,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.669960,0.591502,0.586922,0.572859,0.556116,0.595472,0.039237,7
24,0.602393,0.110707,0.222243,0.028891,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.802560,0.770262,0.842795,0.809031,0.728760,0.790682,0.038587,3
25,0.013401,0.013572,0.000000,0.000000,2000,auto,ploy,"{'C': 2000, 'gamma': 'auto', 'kernel': 'ploy'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
26,0.647464,0.063799,0.094996,0.039253,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.759899,-0.515242,-0.712308,-0.740602,-0.233922,-0.592395,0.199428,28
27,0.675444,0.092063,0.042662,0.014292,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.669818,0.588888,0.587151,0.572793,0.557014,0.595133,0.039071,9
28,0.585644,0.049721,0.185719,0.011548,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.802768,0.770250,0.842539,0.809016,0.728620,0.790639,0.038576,4
29,0.009745,0.008639,0.000000,0.000000,2000,scale,ploy,"{'C': 2000, 'gamma': 'scale', 'kernel': 'ploy'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
30,0.601498,0.048621,0.116859,0.025716,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.673614,-0.519065,-0.737960,-0.768723,-0.254425,-0.590757,0.188926,27
31,0.673879,0.047431,0.069496,0.024119,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.669818,0.588888,0.587151,0.572793,0.557014,0.595133,0.039071,9
32,0.722677,0.043719,0.215012,0.042294,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.805919,0.778044,0.852323,0.816701,0.736721,0.797942,0.038773,1
33,0.009377,0.006390,0.000000,0.000000,3000,auto,ploy,"{'C': 3000, 'gamma': 'auto', 'kernel': 'ploy'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
34,0.775101,0.088750,0.118915,0.016882,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-2.229165,-1.844379,-2.283759,-2.102714,-1.068503,-1.905704,0.445204,29
35,0.923597,0.096356,0.078921,0.027052,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.669814,0.588850,0.587086,0.569527,0.557016,0.594459,0.039466,11
36,0.824117,0.104667,0.206896,0.017374,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.806052,0.778012,0.852141,0.816684,0.736558,0.797890,0.038781,2
37,0.009963,0.010033,0.000000,0.000000,3000,scale,ploy,"{'C': 3000, 'gamma': 'scale', 'kernel': 'ploy'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
38,0.720401,0.036397,0.077643,0.017032,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.075877,-1.854717,-2.365879,-2.184518,-1.144632,-1.925125,0.423887,30
39,0.617265,0.085735,0.082551,0.037620,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.669814,0.588850,0.587086,0.569527,0.557016,0.594459,0.039466,11

In [24]:
age_input = float(input("Age: "))
bmi_input = float(input("BMI: "))
children_input = float(input("Children: "))
sex_male_input = int(input("Sex Male (0 or 1): "))
smoker_yes_input = int(input("Smoker Yes (0 or 1): "))

Age:  32
BMI:  43
Children:  2
Sex Male (0 or 1):  0
Smoker Yes (0 or 1):  1

In [28]:
print(independent.columns)

Index(['age', 'bmi', 'children', 'sex_male', 'smoker_no', 'smoker_yes'], dtype='object')

In [30]:
sex_female_input = 1 - sex_male_input

Future_Prediction = grid.predict([[
    age_input,
    bmi_input,
    children_input,
    sex_male_input,
    smoker_yes_input,
    sex_female_input
]])

print(Future_Prediction)

[17126.11013289]