In [36]:
#importing the libaries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [37]:
# Reading the dataset
dataset=pd.read_csv("insurance_pre.csv")

In [38]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [39]:
dataset=pd.get_dummies(dataset)

In [40]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [41]:
dataset = dataset.astype({
    'sex_female': int,
    'sex_male': int,
    'smoker_no': int,
    'smoker_yes': int,
})

In [42]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,1,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0
2,28,33.000,3,4449.46200,0,1,1,0
3,33,22.705,0,21984.47061,0,1,1,0
4,32,28.880,0,3866.85520,0,1,1,0
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0
1334,18,31.920,0,2205.98080,1,0,1,0
1335,18,36.850,0,1629.83350,1,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0
1337,61,29.070,0,29141.36030,1,0,0,1

In [43]:
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)

In [44]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,1,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0
2,28,33.000,3,4449.46200,0,1,1,0
3,33,22.705,0,21984.47061,0,1,1,0
4,32,28.880,0,3866.85520,0,1,1,0
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0
1334,18,31.920,0,2205.98080,1,0,1,0
1335,18,36.850,0,1629.83350,1,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0
1337,61,29.070,0,29141.36030,1,0,0,1

In [12]:
dataset.drop(columns=['sex_female'], inplace=True)

In [13]:
dataset

      age     bmi  children      charges  sex_male  smoker_no  smoker_yes
0      19  27.900         0  16884.92400         0          0           1
1      18  33.770         1   1725.55230         1          1           0
2      28  33.000         3   4449.46200         1          1           0
3      33  22.705         0  21984.47061         1          1           0
4      32  28.880         0   3866.85520         1          1           0
...   ...     ...       ...          ...       ...        ...         ...
1333   50  30.970         3  10600.54830         1          1           0
1334   18  31.920         0   2205.98080         0          1           0
1335   18  36.850         0   1629.83350         0          1           0
1336   21  25.800         0   2007.94500         0          1           0
1337   61  29.070         0  29141.36030         0          0           1

[1338 rows x 7 columns]

In [45]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [46]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_no',
       'smoker_yes']]

In [47]:
independent

      age     bmi  children  sex_male  smoker_no  smoker_yes
0      19  27.900         0         0          0           1
1      18  33.770         1         1          1           0
2      28  33.000         3         1          1           0
3      33  22.705         0         1          1           0
4      32  28.880         0         1          1           0
...   ...     ...       ...       ...        ...         ...
1333   50  30.970         3         1          1           0
1334   18  31.920         0         0          1           0
1335   18  36.850         0         0          1           0
1336   21  25.800         0         0          1           0
1337   61  29.070         0         0          0           1

[1338 rows x 6 columns]

In [48]:
dependent=dataset[['charges']]

In [49]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [50]:
from  sklearn.ensemble  import  RandomForestRegressor

In [51]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion': ['squared_error', 'absolute_error'],'max_features': ['sqrt', 'log2', 1.0],'n_estimators': [10, 100]}
grid = GridSearchCV(estimator=RandomForestRegressor(random_state=0), param_grid=param_grid, cv=5, scoring='r2', refit=True, verbose=3, n_jobs=-1)

grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

E:\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=0), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['sqrt', 'log2', 1.0],
                         'n_estimators': [10, 100]},
             scoring='r2', verbose=3)

In [53]:
# print best parameter after tuning
#print (grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)
# print classification report
from sklearn.metrics import r2_score 
#calculate R2 score
r_score= r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8730836728299776

In [54]:
table=pd.DataFrame.from_dict(re)

In [55]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.459402,0.030384,0.030966,0.008357,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.799029,0.734545,0.823542,0.801864,0.764689,0.784734,0.031384,9
1,3.725837,0.087067,0.189884,0.032672,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.809528,0.765268,0.841034,0.825919,0.765817,0.801513,0.031015,1
2,0.428522,0.024643,0.055159,0.024095,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.799029,0.734545,0.823542,0.801864,0.764689,0.784734,0.031384,9
3,3.693055,0.056909,0.197298,0.014523,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.809528,0.765268,0.841034,0.825919,0.765817,0.801513,0.031015,1
4,0.541840,0.055671,0.046775,0.023181,squared_error,1.0,10,"{'criterion': 'squared_error', 'max_features':...",0.762961,0.724171,0.824180,0.774333,0.758679,0.768865,0.032329,12
5,5.395345,0.095101,0.186930,0.014526,squared_error,1.0,100,"{'criterion': 'squared_error', 'max_features':...",0.797462,0.752807,0.834800,0.802480,0.767473,0.791005,0.028650,7
6,1.049030,0.073303,0.053943,0.021411,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.782692,0.767198,0.824168,0.816785,0.769807,0.792130,0.023847,5
7,10.083894,0.091411,0.172748,0.023311,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.803729,0.769400,0.842503,0.822588,0.765962,0.800836,0.029739,3
8,1.206002,0.104696,0.051855,0.025101,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.782692,0.767198,0.824168,0.816785,0.769807,0.792130,0.023847,5
9,8.795628,0.065293,0.125000,0.027512,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.803729,0.769400,0.842503,0.822588,0.765962,0.800836,0.029739,3
10,1.778593,0.057388,0.076132,0.029100,absolute_error,1.0,10,"{'criterion': 'absolute_error', 'max_features'...",0.771497,0.759020,0.814556,0.788142,0.753704,0.777384,0.022046,11
11,9.117567,0.488206,0.066366,0.021535,absolute_error,1.0,100,"{'criterion': 'absolute_error', 'max_features'...",0.782762,0.765636,0.824388,0.796526,0.755531,0.784969,0.024218,8

In [57]:
age_input = float(input("Age: "))
bmi_input = float(input("BMI: "))
children_input = float(input("Children: "))
sex_male_input = int(input("Sex Male (0 or 1): "))
smoker_yes_input = int(input("Smoker Yes (0 or 1): "))

Age:  32
BMI:  43
Children:  1
Sex Male (0 or 1):  1
Smoker Yes (0 or 1):  1

In [58]:
print(independent.columns)

Index(['age', 'bmi', 'children', 'sex_male', 'smoker_no', 'smoker_yes'], dtype='object')

In [59]:
sex_female_input = 1 - sex_male_input

Future_Prediction = grid.predict([[
    age_input,
    bmi_input,
    children_input,
    sex_male_input,
    smoker_yes_input,
    sex_female_input
]])

print(Future_Prediction)

[14808.9336808]